export const FILTER_BOTTOM_LIST = [
  { id: 1, text: '강남구', link: '/' },
  { id: 2, text: '강동구', link: '/' },
  { id: 3, text: '강북구', link: '/' },
  { id: 4, text: '강서구', link: '/' },
  { id: 5, text: '관악구', link: '/' },
  { id: 6, text: '광진구', link: '/' },
  { id: 7, text: '구로구', link: '/' },
  { id: 8, text: '금천구', link: '/' },
  { id: 9, text: '노원구', link: '/' },
  { id: 10, text: '도봉구', link: '/' },
  { id: 11, text: '동대문구', link: '/' },
  { id: 12, text: '동작구', link: '/' },
  { id: 13, text: '마포구', link: '/' },
  { id: 14, text: '서대문구', link: '/' },
  { id: 15, text: '서초구', link: '/' },
  { id: 16, text: '상동구', link: '/' },
  { id: 17, text: '성북구', link: '/' },
  { id: 18, text: '송파구', link: '/' },
  { id: 19, text: '양천구', link: '/' },
  { id: 20, text: '영등포구', link: '/' },
  { id: 21, text: '용산구', link: '/' },
  { id: 22, text: '은평구', link: '/' },
  { id: 23, text: '종로구', link: '/' },
  { id: 24, text: '중구', link: '/' },
  { id: 25, text: '중랑구', link: '/' },
];
