export const FILTER_BOTTOM_LIST = [
  { id: 1, selectValue: '강남구' },
  { id: 2, selectValue: '강동구' },
  { id: 3, selectValue: '강북구' },
  { id: 4, selectValue: '강서구' },
  { id: 5, selectValue: '관악구' },
  { id: 6, selectValue: '광진구' },
  { id: 7, selectValue: '구로구' },
  { id: 8, selectValue: '금천구' },
  { id: 9, selectValue: '노원구' },
  { id: 10, selectValue: '도봉구' },
  { id: 11, selectValue: '동대문구' },
  { id: 12, selectValue: '동작구' },
  { id: 13, selectValue: '마포구' },
  { id: 14, selectValue: '서대문구' },
  { id: 15, selectValue: '서초구' },
  { id: 16, selectValue: '상동구' },
  { id: 17, selectValue: '성북구' },
  { id: 18, selectValue: '송파구' },
  { id: 19, selectValue: '양천구' },
  { id: 20, selectValue: '영등포구' },
  { id: 21, selectValue: '용산구' },
  { id: 22, selectValue: '은평구' },
  { id: 23, selectValue: '종로구' },
  { id: 24, selectValue: '중구' },
  { id: 25, selectValue: '중랑구' },
];
