export const FILTERRING_BOX = [
  {
    id: 1,
    title: '시간',
    titleEng: 'time',
    select: [
      { id: 1, selectValue: '00:00' },
      { id: 2, selectValue: '01:00' },
      { id: 3, selectValue: '02:00' },
      { id: 4, selectValue: '03:00' },
      { id: 5, selectValue: '04:00' },
      { id: 6, selectValue: '05:00' },
      { id: 7, selectValue: '06:00' },
      { id: 8, selectValue: '07:00' },
      { id: 9, selectValue: '08:00' },
      { id: 10, selectValue: '09:00' },
      { id: 11, selectValue: '10:00' },
      { id: 12, selectValue: '11:00' },
      { id: 13, selectValue: '12:00' },
      { id: 14, selectValue: '13:00' },
      { id: 15, selectValue: '14:00' },
      { id: 16, selectValue: '15:00' },
      { id: 17, selectValue: '16:00' },
      { id: 18, selectValue: '17:00' },
      { id: 19, selectValue: '18:00' },
      { id: 20, selectValue: '19:00' },
      { id: 21, selectValue: '20:00' },
      { id: 22, selectValue: '21:00' },
      { id: 23, selectValue: '22:00' },
      { id: 24, selectValue: '23:00' },
    ],
  },
  {
    id: 2,
    title: '연령대',
    titleEng: 'age',
    select: [
      { id: 1, selectValue: '20대' },
      { id: 2, selectValue: '30대' },
      { id: 3, selectValue: '40대' },
      { id: 4, selectValue: '50대' },
      { id: 5, selectValue: '60대' },
      { id: 6, selectValue: '70대' },
      { id: 7, selectValue: '80대' },
      { id: 8, selectValue: '무관' },
    ],
  },
  {
    id: 3,
    title: '성별',
    titleEng: 'gender',
    select: [
      { id: 1, selectValue: '남성' },
      { id: 2, selectValue: '여성' },
      { id: 3, selectValue: '무관' },
    ],
  },
];
